
function 优化日常领取物品()

	--使用背包物品 
	UseItem(0,"真元精珀")
	UseItem(0,"真元精珀")
	UseItem(0,"真元精珀")
	UseItem(0,"苍鹤药魄")
	UseItem(0,"苍鹤药魄")
	UseItem(0,"苍鹤药魄")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"释灵浆")
	UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"真元珀")
        UseItem(0,"真元珀")
	UseItem(0,"御赐令赏")
	UseItem(0,"御赐令赏")
	UseItem(0,"御赐令赏")
	UseItem(0,"御赐令赏")
	UseItem(0,"御赐令赏")
	UseItem(0,"御赐令赏")
	UseItem(0,"凝息丸")
	UseItem(0,"凝息丸")
	UseItem(0,"凝息丸")
	UseItem(0,"凝息丸")
	UseItem(0,"凝息丸")
	UseItem(0,"凝息丸")

	
end

优化日常领取物品()

